### ISSUE TITLE
Node order invariance in generating initial edge features

### ISSUE THREAD

**Issue by mohith-sakthivel** [nianticlabs/relpose-gnn#1]
https://github.com/nianticlabs/relpose-gnn/blob/e69e05f9a7d4101ac8e58086a97ae003b5ebe788/python/niantic/modules/posenet.py#L1014-L1017

Hello,
Thanks for sharing the code for this cool paper. I was going through your implementation and can't really understand why edge direction invariance is introduced in creating the initial edge features.

Since we are regressing relative pose, shouldn't we ensure that features are different for different edge directions? The later edge updates in the GNN do account for the edge direction. But why is this invariance explicitly introduced in creating the initial edge features?

**Comment by 0zgur0** [comment]
It is only during initialization at the end they learn different representations for different directions. You can also try to initialize differently but probably for training stability, this would be a better choice I think.
