### ISSUE TITLE
Question about pose normalization

### ISSUE THREAD

**Issue by liuyuzhenn** [nianticlabs/relpose-gnn#5]
Thanks for sharing the code for the paper! 
However, when going through the code about data loading, I feel confused about the normalization procedure: 
In python\niantic\datasets\seven_scenes.py Line 121, the poses seem to undergo a normalization operation, why?
Will it influence the evaluation since the scale of camera translation is modified?

**Comment by 0zgur0** [comment]
that normalization operation was based on previous works - yes, it should affect the evaluation.
